---
- name: Clone repository for DDEV
  shell: |
    curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null

- name: Activate a repository for DDEV
  shell: |
    echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list

- name: Installation of DDEV
  apt:
    name: ddev
    state: present
    update_cache: yes
