---
- name: Verify
  hosts: all
  become: false
  tasks:
    - name: Check ddev binary is available
      ansible.builtin.command: ddev --version
      register: ddev_version
      changed_when: false
      become_user: "ddev"
